
version: "2"
services:
  api:
    image: node:latest
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/home/node/api/
    working_dir: /home/node/api
    command: yarn start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:latest
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - api
  #   networks:
  #     - backend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100MB"
  #       max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis: